version: '3.7'
services:
  web:
    container_name: "docker_compose_realworld"
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
    - .:/app
    ports:
      - "3001:3000"
    environment: 
      - NODE_ENV=development
